name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |
          pip install -r requirements.txt

          dvc pull wine_quality.csv
          dvc repro

          git fetch --prune

          echo "## MODEL METRICS:" >> report.md
          dvc metrics diff --show-md main > report.md
          
          echo "## DATA VISUALIZATION:" >> report.md
          cml-publish rfc_importances.png --md >> report.md
          
          cml-send-comment report.md
