name: wine_quality_classification
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      
      - name: Install requirements
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run black
        run: |
          black train.py
      
      - name: Run Pylint
        run: |
          python lint.py --path train.py --threshold 7
        
      - name: Run DVC
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |
          dvc pull wine_quality.csv
      
      - name: Run Pytest
        run: |
          pytest test.py
      
      - name: Run Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc repro
          dvc push

          git fetch --prune

          echo "## MODEL METRICS:" >> report.md
          dvc metrics diff --show-md main > report.md
          
          echo "## DATA VISUALIZATION:" >> report.md
          cml-publish rfc_importances.png --md >> report.md
          
          cml-send-comment report.md
